// Detection Name: 
// Description: 
// Author: Michael Jost
// Date: 
// Data Source: Microsoft Sentinel
// MITRE ATT&CK: 
// Severity: High
// False Positives: 
// Notes: Tune based on service principal creation patterns

DeviceProcessEvents
  | where FileName =~ "esentutl.exe"
  | where ProcessCommandLine has_all("/y","/d",":","/o")
  | project TimeGenerated, DeviceName, ActionType, AccountName, ProcessCommandLine, FileName, FolderPath, ProcessId, InitiatingProcessFileName, InitiatingProcessCommandLine, InitiatingProcessFolderPath, InitiatingProcessId, InitiatingProcessParentFileName, InitiatingProcessParentId, InitiatingProcessAccountDomain, InitiatingProcessAccountName, ProcessVersionInfoCompanyName, ProcessVersionInfoProductName, ProcessVersionInfoProductVersion, ProcessVersionInfoInternalFileName, ProcessVersionInfoOriginalFileName, ProcessVersionInfoFileDescription, FileSize, SHA256, DeviceId, ReportId
