// Detection Name: 
// Description: 
// Author: Michael Jost
// Date: 
// Data Source: Microsoft Sentinel
// MITRE ATT&CK: 
// Severity: High
// False Positives: 
// Notes: Tune based on service principal creation patterns

DeviceProcessEvents
  | where ProcessVersionInfoOriginalFileName =~"rclone.exe"
  | where FileName != "rclone.exe"
  | project TimeGenerated, DeviceName, ActionType, FolderPath, FileName, InitiatingProcessFileName, InitiatingProcessAccountName, ProcessVersionInfoOriginalFileName
