// Detection Name: 
// Description: 
// Author: Michael Jost
// Date: 
// Data Source: Microsoft Sentinel
// MITRE ATT&CK: 
// Severity: High
// False Positives: 
// Notes: Tune based on service principal creation patterns

DeviceProcessEvents
  | where ProcessCommandLine has_any ("sftp://","scp://","ftps://")
  | where ProcessCommandLine has_any ("console")
  | project TimeGenerated, DeviceName, ActionType, AccountName, AccountDomain, FileName, FolderPath, ProcessId, ProcessCommandLine, InitiatingProcessFileName, InitiatingProcessCommandLine, InitiatingProcessFolderPath, InitiatingProcessId, InitiatingProcessParentFileName, InitiatingProcessParentId, InitiatingProcessAccountDomain, InitiatingProcessAccountName, ProcessVersionInfoCompanyName, ProcessVersionInfoProductName, ProcessVersionInfoProductVersion, ProcessVersionInfoInternalFileName, ProcessVersionInfoOriginalFileName, ProcessVersionInfoFileDescription, FileSize, SHA256, DeviceId, ReportId
  | order by TimeGenerated
